title = 'Janine Lindenmann | Freie Rednerin'
baseURL = 'https://www.janine-lindenmann.de'
copyright = "Copyright © {{year}}"
languageCode = "de"
defaultContentLanguage = "de"

enableInlineShortcodes = true
enableEmoji = false
enableRobotsTXT = true
pagination.pagerSize = 6

disableKinds = ["taxonomy", "term", "RSS"]

[sitemap]
    changefreq = "monthly"
    filename = "sitemap.xml"
    priority = 0.5

[params]
    cdn = false
    mainSections = []
    keywords = ["Hochzeit", "Traurednerin", "Rede", "Freie Rednerin", "Südschwarzwald", "konfessionslos", "zweisprachig", "weltlich", "Traurednerin gesucht", "Hochzeitsrednerin", "Freie Trauung", "Willkommensfest", "Feier", "Zeremonie", "Symbolische Handlung", "Ritual"]

[params.brand]
    logo = "/img/icons/banner-full.svg"
    name = "Janine Lindenmann | Freie Rednerin (IHK)"
    logoShort = "/img/icons/banner-narrow.svg"
    nameShort = "Janine Lindenmann"
    tagline = "Euer Moment - meine Worte. Klar. Tiefgründig. Ergreifend."

[params.meta]
    baseOGImage = "/img/brand.png"

[[menus.main]]
    identifier = "/"
    name = "Start"
    url = "/"
    weight = 10
[[menus.main]]
    identifier = "about-me"
    name = "Über mich"
    url = "/about-me/"
    weight = 20
[[menus.main]]
    identifier = "zeremonien"
    name = "Zeremonien"
    weight = 30
[[menus.main]]
    parent = "zeremonien"
    name = "Freie Trauung"
    url = "/freie-trauung/"
    weight = 31
[[menus.main]]
    parent = "zeremonien"
    name = "Kinder<wbr>willkommens<wbr>fest"
    url = "/kinderwillkommensfest/"
    weight = 32
[[menus.main]]
    identifier = "kontakt"
    name = "Kontakt"
    url = "/kontakt/"
    weight = 40

[[menus.footer]]
    identifier = "impressum"
    name = "Impressum"
    url = "/impressum/"
    weight = 10
[[menus.footer]]
    identifier = "datenschutz"
    name = "Datenschutz"
    url = "/datenschutz/"
    weight = 20

[outputs]
    home = ["html"]

[markup.goldmark.renderer]
    unsafe = true

[markup.goldmark.parser.attribute]
    block = true
    title = true

[markup.goldmark.extensions]
    strikethrough = true

[markup.goldmark.extensions.extras.delete]
    enable = true

[markup.goldmark.extensions.extras.insert]
    enable = true

[markup.goldmark.extensions.extras.mark]
    enable = true

[markup.goldmark.extensions.extras.subscript]
    enable = true

[markup.goldmark.extensions.extras.superscript]
    enable = true

[module]
    [module.hugoVersion]
      extended = true
      min = "0.129.0"
    [[module.mounts]]
      source = "assets"
      target = "assets"

[privacy.twitter]
    enableDNT = true

[privacy.vimeo]
    enableDNT = true

[privacy.youtube]
    privacyEnhanced = true
