name: CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          submodules: true
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Install Node.js
        uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7
        with:
          node-version: 20.x
      - name: npm ci
        run: npm ci --ignore-scripts
      - name: Lint
        run: npm run lint
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@2752ce1d29631191ea3f27c23495fa06139a5b78 # v3.2.1
        with:
          hugo-version: '0.139.0'
          extended: true
      - name: Build
        run: npm run build
      - name: Dependabot Auto Merge
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
        run: |
          echo "$GITHUB_CONTEXT"
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GH_ACTION_MERGER_TOKEN }}
