name: 🚀 Deploy website on tag
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  build:
    if: github.event.base_ref == 'refs/heads/main'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: ↧ Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: ↧ npm ci
        run: npm ci
      - name: ⚛ Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.139.0'
          extended: true
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: ⚙ Build
        run: npm run build
      - name: 🏷️ Get tag name
        run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/*/} | tr / -)" >> $GITHUB_ENV
      - name: 📂 Archive
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: release-diff
          folder: public
          clean: true
          commit-message: Release ${{ env.TAG_NAME }}
      - name: 🎉 Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: web27.alfahosting-server.de
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          protocol: ftps
          local-dir: ./public/
          server-dir: /
          security: loose
          port: 21
